// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAndDjuf884BA20OOY6b9SBa19z4kxgqjI',
    appId: '1:507327301223:web:821c19848ab8e85a4bf6c2',
    messagingSenderId: '507327301223',
    projectId: 'testing-firebase-974bd',
    authDomain: 'testing-firebase-974bd.firebaseapp.com',
    databaseURL: 'https://testing-firebase-974bd.firebaseio.com',
    storageBucket: 'testing-firebase-974bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADBzw0Fjt9P2jGz3K7FVBw8MOHsKDhp0s',
    appId: '1:507327301223:android:f3c451801b74f7c14bf6c2',
    messagingSenderId: '507327301223',
    projectId: 'testing-firebase-974bd',
    databaseURL: 'https://testing-firebase-974bd.firebaseio.com',
    storageBucket: 'testing-firebase-974bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4HwBSzVQTQnZ3lYZAn194z_jIu_ffWc',
    appId: '1:507327301223:ios:6b60f131deb0cab34bf6c2',
    messagingSenderId: '507327301223',
    projectId: 'testing-firebase-974bd',
    databaseURL: 'https://testing-firebase-974bd.firebaseio.com',
    storageBucket: 'testing-firebase-974bd.appspot.com',
    androidClientId: '507327301223-r5kb48758g8mp43nm5eppja6ka3lvsct.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4HwBSzVQTQnZ3lYZAn194z_jIu_ffWc',
    appId: '1:507327301223:ios:3417cec92d267e214bf6c2',
    messagingSenderId: '507327301223',
    projectId: 'testing-firebase-974bd',
    databaseURL: 'https://testing-firebase-974bd.firebaseio.com',
    storageBucket: 'testing-firebase-974bd.appspot.com',
    androidClientId: '507327301223-r5kb48758g8mp43nm5eppja6ka3lvsct.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
